name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run:
      - ls /Applications
      - sudo xcode-select -s /Applications/Xcode_11.2.app
      - swift build -v
    - name: Run tests
      run: swift test -v
